development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: live_chat_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: live_chat_production
